version: '3.9'
services:
    lnd:
      image: lightninglabs/lnd:v0.12.0-beta.rc6
      container_name: lnd-testnet-alice
      volumes:
        - docker_shared:/rpc
        # - lnd:/root/.lnd
      ports:
        - 10009:10009
      command: --noseedbackup --no-rest-tls --bitcoin.active --bitcoin.testnet --bitcoin.node=btcd --btcd.rpccert=/rpc/rpc.cert --btcd.rpchost=host.docker.internal:18333 --btcd.rpcuser=devuser --btcd.rpcpass=devpass --rpclisten=localhost:10009 --debuglevel=trace
volumes:
  # shared volume is need to store the btcd rpc certificates and use it within
  # btcctl and lnd containers.
  docker_shared:
    external: true
  lnd:
    driver: local