version: '3.9'
services:
    btcd-simnet:
      image: btcd
      container_name: btcd-simnet
      volumes:
        - btcd_simnet_rpc:/rpc
        - btcd_simnet_data:/data
      ports:
        - 18333:18351
      environment:
        - RPCUSER
        - RPCPASS
        - NETWORK=simnet
        - DEBUG=info
        - MINING_ADDRESS
      entrypoint: ["./start-btcd.sh"]
      # command: btcd --simnet --txindex --rpcuser=devuser --rpcpass=devpass --datadir=/data --logdir=/data --rpccert=/rpc/rpc.cert --debuglevel=info
      # --notls
volumes:
  # shared volume is need to store the btcd rpc certificates and use it within
  # btcctl and lnd containers.
  btcd_simnet_rpc:
    external: true
  # bitcoin volume is needed for maintaining blockchain persistence
  # during btcd container recreation.
  btcd_simnet_data:
    external: true