version: '3.9'

networks:
  spx:

services:
    sphinx-chat:
      image: sphinx-relay
      container_name: sphinx-relay-prod
      volumes:
        - ./volumes/.lnd:/relay/.lnd
      ports:
        - 3001:3001
      command: "npm start"
      environment:
        - PORT=3001
        - NODE_ENV=production
        - LND_IP=docker-host
        - LND_PORT=11009
        - MACAROON_LOCATION=/relay/.lnd/macaroons/admin.macaroon
        - TLS_LOCATION=/relay/.lnd/cert/tls.cert
        - PUBLIC_URL=localhost:3001
      networks:
        - spx

    docker-host:
      image: qoomon/docker-host
      cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
      mem_limit: 8M
      restart: on-failure
      networks:
        - spx
