version: '3.9'
services:
    sphinx-chat:
      image: sphinx-relay:docker
      container_name: sphinx-relay-prod
      volumes:
        - ./volumes/.lnd:/relay/.lnd
      ports:
        - 3300:3300
      command: "npm start"
      environment:
        - PORT=3300
        - NODE_IP=0.0.0.0
        - NODE_ENV=production
        - LND_IP=192.168.65.2
        - LND_PORT=11009
        - MACAROON_LOCATION=/relay/.lnd/macaroons/admin.macaroon
        - TLS_LOCATION=/relay/.lnd/cert/tls.cert
        - PUBLIC_URL=localhost:3300
      # network_mode: host
